### ISSUE TITLE
README.MD link to 2017

### ISSUE THREAD

**Issue by timosachsenberg** [OBF/GSoC#12]
The link to the 2016 GSoC is set to http://obf.github.io/GSoC/ which points to GSoC of 2017

**Comment by peterjc** [comment]
Hmm, right now http://www.open-bio.org/wiki/Google_Summer_of_Code_2016 points at http://obf.github.io/GSoC/

However, we could move content on http://www.open-bio.org/wiki/Google_Summer_of_Code which is currently from 2016 to that page? Or go back in the git history for http://obf.github.io/GSoC/ ...

CC @kblin

**Comment by kblin** [comment]
I've restored the historic 2016 ideas page and linked to that. Do you think any of the other parts need saving? They're always in the git history, of course.

**Comment by peterjc** [comment]
I''ve updated https://www.open-bio.org/wiki/Google_Summer_of_Code_2016 to point there, http://obf.github.io/GSoC/historic/2016-ideas/

**Comment by kblin** [comment]
Looks good to me. Does this solve the issue?
