### ISSUE TITLE
retitle to indicate that this isn't used for 2020

### ISSUE THREAD

**Issue by mr-c** [OBF/GSoC#47]
and add link to https://mailman.open-bio.org/pipermail/gsoc/2020/000980.html

**Comment by peterjc** [comment]
Do you have editing rights here @mr-c? If so a pull request to make the README point here for 2020 sounds sensible:

https://www.open-bio.org/events/gsoc/gsoc-project-ideas/

**Comment by yochannah** [comment]
resolved by #50 🚀
